server:
  port: 9001
spring:
  application:
    name: USER
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr} #指定注册中心地址
        service: ${spring.application.name}
      server-addr: http://39.101.133.83:8848 #指定nacos服务地址