spring:
  thymeleaf:
    # 关闭thymeleaf缓存
    cache: false
  # 数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.133.83:3939/seckill?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: p17671735420.
    hikari:
      # 别名
      pool-name: DateHikariCP
      # 最大连接数
      maximum-pool-size: 10
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存货最大时间
      idle-timeout: 1800000
      # 最大存活时间
      max-lifetime: 1800000
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接超时
      connection-timeout: 30000
      # 心跳机制，测试连接是否可用
      connection-test-query: SELECT 1
  # reids配置
  redis:
    # 服务器地址
    host: 39.101.133.83
    # 端口
    port: 3939
    # 库选择
    database: 0
    # 超时时间
    timeout: 10000ms
    # 密码
    password: p17671735420.
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5
# mybatis-plus配置
mybatis-plus:
  # ??mapper路径
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名
  type-aliases-package: com.haha.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
