server:
  port: 8761 #注册中心默认端口
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #指定注册中心地址
    fetch-registry: false #关闭立即注册，只不过时启动是不注册（是否注册到eureka服务中）
    register-with-eureka: false #当前只单纯的作为服务的注册中心（是否拉取其他的服务）
  instance:
    lease-renewal-interval-in-seconds:
    lease-expiration-duration-in-seconds:
  server:
    enable-self-preservation:
    eviction-interval-timer-in-ms:
spring:
  application:
    name: EUREKASERVER #服务名不要有下划线且不能重复，不区分大小写，推荐使用大写