server:
  port: 9011
spring:
  application:
    name: CATEGORY
  cloud:
    consul:
      host: localhost
      port: 8500
    feign:
      client:
        config:
          PRODUCTS:
            connectTimeout: 5000  #配置指定服务连接超时
            readTimeout: 5000            #配置指定服务等待超时
            #feign.client.config.default.connectTimeout=5000  		#配置所有服务连接超时
            #feign.client.config.default.readTimeout=5000			#配置所有服务等待超时
            loggerLevel: full
            #feign.client.config.default.loggerLevel=full  #全局开启服务日志展示
logging:
  level:
    com.haha.feignclients: debug #指定feign调用客户端对象所在包,必须是debug级别